import About from "@/components/About";
import Contact from "@/components/Contact";
import Explore from "@/components/Explore";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import Menu from "@/components/Menu";
import Navbar from "@/components/Navbar";
import Shop from "@/components/Shop";
import Team from "@/components/Team";
import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Hero />
        <About />
        <Explore />
        <Menu />
        <Team />
        <Shop />
        <Contact />
        <Footer />
      </main>
    </>
  );
}
